### ISSUE TITLE
Log rotation?

### ISSUE THREAD

**Issue by burner1024** [devforth/OnLogs#5]
Hi!
The project looks cool. I see it has some log persistence, too. How it is cleaned up, though?
Also, does it have to run as root?

**Comment by LbP22** [comment]
I'll leave it open for some time. If there would be no additional questions, I'll close the issue

**Comment by burner1024** [comment]
So that's not exactly rotation, just manual wipe, right?

**Comment by LbP22** [comment]
Absolutely right. The rotation exactly was in our roadmap, not sure why readme doesn't mentioned it

**Comment by burner1024** [comment]
Got it, thanks.
